### PR TITLE
Replaced screenshot for Create new TestPlan. Fixes #32

### LINKED ISSUE #32: Create new TestPlan image needs update
Version 6.3 has just been released and it updated the Create TP page to Patternfly which means the screenshot on the website needs a refresh.

NOTE: it must be exactly the same size as the existing one because that matters to scaling and scrolling, especially on mobile.

### PR DESCRIPTION
**Pull request by asankov**
Although the issue says to replace the picture with one of the same size, doing so yielded unsatisfactory results, and the picture looked blurred (it may have been because of the high resolution on my laptop). I have added the picture with its original size, and it looked fine, without any problems for mobile phones or tablets.

### CODE REVIEW

**Comment by asankov** [comment]
Also, you may want to block merging, before any approvals have been given

**Review by atodorov — CHANGES_REQUESTED** [review]
The image must be 922x450 pixels. There is a reason for that.

Bigger image may look fine on smaller screens but we cause the browser to load more data, which we don't really need. 

Also sizing is done by width and some of the more taller images are cut off at the bottom. You will have to figure out how to make the image fit the size and look good. 

If your display is too wide change the resolution before taking a screenshot and edit the image if necessary to fit the size constraints. We don't need to be showing every possible widget on the page but it should clearly represent what this page is about.

**Comment by atodorov** [comment]
Also this needs to be against the source branch, b/c master is auto generated via Pelican.

**Comment by asankov** [comment]
Closing PR as it was against the wrong branch. Will open new one

**Comment by atodorov** [comment]
next time `git rebase -i source` and edit the base branch in the PR as well then push.

**Pull request closed without merging**
