### PR TITLE
Convert README into markdown file

### LINKED ISSUE #83: Convert the README to README.md
The `README` is not rendered as markdown because it is missing the file extension `.md`

Raised issue as part of my live stream and one of the viewers will create a PR for you https://youtu.be/cryscnTdqMw

### PR DESCRIPTION
**Pull request by Crease29**
Closes #83

### CODE REVIEW

**Comment by eddiejaoude** [comment]
`3.6` would look better in back tics

**Comment by Crease29** [comment]
Done 🙂

**Comment by atodorov** [comment]
this file gets ovewritten automatically so you have to open your pull request against the source branch - change the settings in the webUI and the rebase the commit.

**Comment by Crease29** [comment]
Done. Is this how you wanted it?

**Comment by atodorov** [comment]
> Done. Is this how you wanted it?

Thanks for your effort but still needs minor adjustments. The file you want to modify is in `content/README`, which you'd have to rename to `content/README.md` and update the contents. All of this is in the `source` branch like you've already done. 

When the website is updated (aka `make github`) the master branch is rebuilt and automatically pushed to GitHub.

**Comment by Crease29** [comment]
Alright, should be fixed now. Sorry for the confusion.

**Review by atodorov — APPROVED** [review]

**Pull request merged**
